# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=64)),
                ('stadium', models.CharField(max_length=64)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to=b'club')),
                ('info', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('level', models.IntegerField(blank=True, default=1, null=True)),
                ('info', models.TextField(blank=True, default=None, null=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to=b'league')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('display_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, default=None, max_length=2, null=True)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to=b'person')),
                ('bdate', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, default=None)),
                ('club', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Club')),
            ],
            options={
                'verbose_name': 'Player history',
                'verbose_name_plural': 'Player histories',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='landing.Person')),
            ],
            bases=('landing.person',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='landing.Person')),
                ('shirt_number', models.IntegerField(blank=True, default=None, null=True)),
                ('is_captain', models.BooleanField(default=False)),
            ],
            bases=('landing.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Club'),
        ),
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.League'),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Player'),
        ),
    ]
