# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b''),
        ),
    ]
