# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
