# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20171204_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhistory',
            name='goals',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='playerhistory',
            name='matches',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
