# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20171204_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
