# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_person_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'club'),
        ),
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'league'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'person'),
        ),
        migrations.AlterField(
            model_name='player',
            name='shirt_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
