# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_person_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhistory',
            name='is_loan',
            field=models.BooleanField(default=False),
        ),
    ]
