# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 22:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logo', models.URLField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('year', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2100)])),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('photo', models.URLField(blank=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Person')),
            ],
            options={
                'verbose_name_plural': 'Coaches',
            },
            bases=('home.person',),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Person')),
                ('position', models.CharField(max_length=128)),
            ],
            bases=('home.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='club',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Club'),
        ),
    ]
